### PR TITLE
Parser + template interfaces

### PR DESCRIPTION
**Pull request by buk0vec**
goated and cracked and parserpilled

### CODE REVIEW

**Comment by buk0vec** [comment]
"review required" oh im sorry, i thought this was america.

**Review by electropicks — APPROVED** [review]

**Comment by buk0vec** [comment]
thanks electropicks, very cool

**Comment by buk0vec** [comment]
oh and ill create issues for requirements + close them out through this pr

**Comment by electropicks** [comment]
thank you

**Pull request merged**
